package exception;

public class Main01 {

	public static void main(String[] args) {

//		사용자의 입력값을 가정
		String[] src = {"9", "2", "1", "5"};
		
//		src의 내용들을 숫자로 변환해서 저장할 배열
		
		int[] arr = new int [3];
		
		try {
			
			for( int i = 0 ; i <src.length ; i++) {
			arr[i] = Integer.parseInt(src[i]);
			System.out.println( arr[i]);
			}
		} catch(NumberFormatException e) {
			System.out.println("에러발생");
			e.printStackTrace();} 
		catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("에러발생");
			e.printStackTrace();
		}catch(Exception e) {
			System.out.println("알 수 없는 에러발생");
			e.printStackTrace();
		} finally {
//			이 블록은 예외의 발생 여부에 상관없이 무조건 실행된다.
			System.out.println("데이터 변환 종료");
		}
		 
		System.out.println("------프로그램 종료-------");
		
		
	}

}
